package FrameBuffer;

import static org.lwjgl.opengl.GL30.GL_RENDERBUFFER;
import static org.lwjgl.opengl.GL30.glBindRenderbuffer;
import static org.lwjgl.opengl.GL30.glDeleteRenderbuffers;
import static org.lwjgl.opengl.GL30.glGenRenderbuffers;
import static org.lwjgl.opengl.GL30.glRenderbufferStorage;
import static org.lwjgl.opengl.GL30.glRenderbufferStorageMultisample;

/* Completed */

public class RenderBuffer {
	//Render buffer ID witch is get then generated by OpenlGL.
	private int ID;
	//Render buffer size.
	private int Width;
	private int Height;
	//Color format example RGB, RGBA, RG, R, ect.
	private int OpenglFormat;
	//Samples number how many nearest pixels effects middle pixel. More samples more graphic processing power it use.
	private int SamlesNumber;
	
	//Constructors for set up first data and generate buffers.
	public RenderBuffer(int Width, int Height, int OpenglFormat, int SamlesNumber	) {
		this.Width 			= Width;
		this.Height 		= Height;
		this.OpenglFormat 	= OpenglFormat;
		this.SamlesNumber 	= SamlesNumber;
		//Generate render buffer in openGL list or collection and return ID.
		ID = glGenRenderbuffers();
		SetUp();
	}
	public RenderBuffer(int Width, int Height, int OpenglFormat						) {
		this.Width 			= Width;
		this.Height 		= Height;
		this.OpenglFormat 	= OpenglFormat;
		this.SamlesNumber 	= 1;
		//Generate render buffer in openGL list or collection and return ID.
		ID = glGenRenderbuffers();
		SetUp();
	}
	
	//Bind "activate" render buffer.
	public void Bind	() {
		glBindRenderbuffer(GL_RENDERBUFFER, ID);
	}
	//disable render buffer.
	public void Unbind	() {
		glBindRenderbuffer(GL_RENDERBUFFER, 0);
	}
	
	//Get render buffer ID used for frame buffer.
	public int GetID	() {
		return ID;
	}
	//Set up render buffer with parameters.
	public void SetUp	() {
		//Activate render buffer.
		Bind();
		
		if(this.SamlesNumber <= 1) {
			//If don't need to store multisample data generate simple render buffer.
			glRenderbufferStorage(GL_RENDERBUFFER, OpenglFormat, Width, Height);
		} else {
			//If us need multisampled texture we generate multisampled render buffer to store additional data for multisampling.
			glRenderbufferStorageMultisample(GL_RENDERBUFFER, this.SamlesNumber, OpenglFormat, Width, Height);
		}
		//Disable render buffer.
		Unbind();
	}
	
	//Disable render buffer and delete it.
	public void CleanUp	() {
		Unbind();
		glDeleteRenderbuffers(ID);
	}
}